### ISSUE TITLE
Add command to uninstall unused non-core modules

### ISSUE THREAD

**Issue by hismightiness** [cantarus/PolyDeploy#11]
One of the most common use cases we have that would involve this extension is performing client upgrades.  One of my first steps when doing upgrades for clients is to uninstall any unused extension that's not an out-of-the-box extension.  An incredible number of DNN sites have 5+ extensions on the site that were installed and never put onto a page.  These extensions often cause module installation/upgrade conflicts and DNN upgrade issues.

It would be great to have a command to automatically uninstall all unused, non-core, extensions at once.

**Comment by StevenFisherCantarus** [comment]
Hi Will, 

We have discussed the option of adding this in however I dont think it sits well with the overall purpose of PolyDeploy. However this would be a great extension to DNN Prompt. 

Steve
