### ISSUE TITLE
File Extension not allowed?

### ISSUE THREAD

**Issue by leedavi** [cantarus/PolyDeploy#111]
When installing a module, which installs in DNN I get this error....

![image](https://github.com/DNNCommunity/PolyDeploy/assets/5583141/8959c1c9-4ec4-4f3c-bca1-b3f85cb5fa49)

However, on the log it tells me it has installed?

Is there some issue with file extensions?  I can understand some file extensions being blocked. but ".rules" ?  why ?  Or is this a bug?

**Comment by david-poindexter** [comment]
@leedavi if you want to allow that file type, then you would need to add the extension to the allowable file extensions in DNN.

**Comment by leedavi** [comment]
Ok, thx.  I will try it.  Sorry I should have thought of that.

**Comment by david-poindexter** [comment]
😀 no worries - happy to help.

**Comment by WillStrohl** [comment]
It sounds like this can be closed now.  Is that correct?

**Comment by leedavi** [comment]
This is closed, but if this module ever finds it's way into DNN I think it should work on the same rules as the current module install.

i.e. not on the file extension list.
