### ISSUE TITLE
Can't build the project.

### ISSUE THREAD

**Issue by mardon1975** [cantarus/PolyDeploy#14]
When we pull down the latest zip and try to build we get the following errors.
NuGet Package restore failed for project PolyDeploy: Unable to find version '7.0.0' of package 'DotNetNuke_Community_System.Web.Http'.
NuGet Package restore failed for project PolyDeploy: Unable to find version '7.0.0' of package 'DotNetNuke_Community_System.Net.Http.Formatting'.
NuGet Package restore failed for project PolyDeploy: Unable to find version '7.0.0' of package 'DotNetNuke_Community_Newtonsoft.Json'.
NuGet Package restore failed for project PolyDeploy: Unable to find version '7.0.0' of package 'DotNetNuke_Community_System.Net.Http'.
NuGet Package restore failed for project PolyDeploy: Unable to find version '7.0.0' of package 'DotNetNuke_Community_DotNetNuke.Web'.
NuGet Package restore failed for project PolyDeploy: Unable to find version '7.0.0' of package 'DotNetNuke_Community_DotNetNuke.Web.Client'.
NuGet Package restore failed for project PolyDeploy: Unable to find version '7.0.0' of package 'DotNetNuke_Community_DotNetNuke'.

**Comment by can-anierzad** [comment]
This was also raised in issue #1 which was closed by MR #7.

If you checkout the `development` branch you should be able to build the solution normally.

I hope this helps.
