### ISSUE TITLE
Event Log Paging - Struggles at large number of pages

### ISSUE THREAD

**Issue by can-martin-kennish** [cantarus/PolyDeploy#21]
The paging for the event log struggles at large numbers of pages (see the image below for an example). Whist you can navigate to pages over 128, you have to use the next button, **repeatedly**. It also displays the logs oldest first rather than latest first.

![polydeploy event log paging](https://user-images.githubusercontent.com/36661396/40874052-535894c6-6662-11e8-95a4-e93352ad7b21.png)

I suggest that:
- First and last pages buttons be added
- The number of displayed pages cuts down to 5 either side of the current page
- The order of the log is reversed to be latest first

**Comment by can-anierzad** [comment]
Fixed by #45.
