### ISSUE TITLE
Provide download via GitHub releases

### ISSUE THREAD

**Issue by SNiels** [cantarus/PolyDeploy#22]
There's [another issue talking](https://github.com/cantarus/PolyDeploy/issues/3) about adding PolyDeploy to DNN store which is great.
I'm a DNN newb and for newcomers it would be easier to just be able to download PolyDeploy directly from GitHub without the hassle of logging in and going through the "purchasing" flow on the DNN store.

**Comment by can-anierzad** [comment]
Hi @SNiels, we have actually already done that, you can find an install zip for each released version of PolyDeploy here: https://github.com/cantarus/PolyDeploy/releases

**Comment by SNiels** [comment]
I was looking for "Releases" under one of the main tabs. Got confused by GitHub interface.
Thanks for clearing that up.
