### ISSUE TITLE
Add command line arguments to allow setting app.config settings.

### ISSUE THREAD

**Issue by SNiels** [cantarus/PolyDeploy#25]
If the "TargetUri", "APIKey", and "EncryptionKey" could be set via command line arguments, or environment variables. The executable file could be more portable and not rely on the app.config.
For CI/CD systems, this would make setting up a Module deploy task easier

**Comment by SNiels** [comment]
I see it in the development branch, that will be a great addition. Thanks!

**Comment by can-anierzad** [comment]
Addressed by #10.
