### ISSUE TITLE
Automatically update web.config on installation and uninstall

### ISSUE THREAD

**Issue by hismightiness** [cantarus/PolyDeploy#4]
PolyDeploy requires that a web.config update is made in order for it to work properly, per the documentation below:

https://github.com/cantarus/PolyDeploy/blob/master/docs/poly-deploy/installation.md

DNN has the XML Merge capability for you to do this via the API, the Configuration Manager, and in the module manifest.  As an administrator, I want to be able to install this module without having to manually make any direct updates to the web.config to reduce the complexity of installation, recycles of the website, and human errors.

(FYI - I already have a fork where I've done the work to send a PR to you once Issue #1 is resolved.)

https://github.com/hismightiness/polydeploy/tree/feature/webconfig-install-update

**Comment by can-anierzad** [comment]
PR #7 should have resolved the build issue Will, raise your PR whenever you're ready 🙂.

**Comment by hismightiness** [comment]
I hope to do this today.  Thanks!  :)

**Comment by StevenFisherCantarus** [comment]
Fix Merged In, Closing this issue
