### ISSUE TITLE
Modules are not installed when the PolyDeploy is being opened from a different view except the Upload one

### ISSUE THREAD

**Issue by PCStefan** [cantarus/PolyDeploy#46]
#### **Environment info:**
> Dnn Platform: v08.04.00
> [PolyDeploy: v0.8.0](https://github.com/cantarus/PolyDeploy/releases/tag/v0.8.0)

#### **Steps to reproduce the issue:**
> 1. Install PolyDeploy on the website and place it on a page under the `Host` page (e.g. `https://local.dnndev.me/Host/Deploy-Modules`). 
> 2. Create a simple DNN module. (i.e. display `Hello World!` from within the View.ascx.cs)
> 3. Install it and modify it to display `Hello PolyDeploy!`. 
> 3. Go to the PolyDeploy page other than the upload page of PolyDeploy.
_e.g. Consider the summary page because the browser decided that it should store that page: `https://local.dnndev.me/Host/Deploy-Modules/portalid/0#!/install/summary`_
> 4. You are automatically redirected to the `upload` page. (I believe that at this point the installation has already been flagged as completed.)
> 5. Upload the module created during step2 and click on `Upload`.
> 6. Proceed by clicking on the `Continue` button once the module has been uploaded.
> 7. See the summary of the installation and continue to summary view.
> 8. An installation will be triggered saying that everything has been installed, but there won't be any AppPool refresh. 

#### **Expected outcome:**
> A successful installation,

**Comment by can-anierzad** [comment]
Resolved by #51.
