### ISSUE TITLE
Add Note Column to IP Address

### ISSUE THREAD

**Issue by hismightiness** [cantarus/PolyDeploy#65]
In many environments, multiple people at multiple locations may need to manage the installation/upgrade of extensions.  It would be useful to have a required `[Note]` (or another more useful name) column added so that everyone knows the context of the given IP address in the table.  

It would also be useful to see this information in the front-end view as well.  

This is especially true today since more and more people are working remotely and they may not have a static IP address.

**Comment by mitchelsellers** [comment]
In Azure this is typically simply "Rule Name" or "Name" for a firewall rule which is essentially what this is for.

**Comment by hismightiness** [comment]
Resolved in release 0.9.3
