### ISSUE TITLE
Add support for IP Address range whitelisting to support Azure Pipelines

### ISSUE THREAD

**Issue by davidjrh** [cantarus/PolyDeploy#80]
Would be nice to have support for IP Address ranges whitelisting to support Azure Pipelines outbound IP Address ranges. By this documentation https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops#ip-addresses-and-range-restrictions, current IP Address ranges in CIDR notation are:
* 13.107.6.0/24
* 13.107.9.0/24
* 13.107.42.0/24
* 13.107.43.0/24

**Comment by bdukes** [comment]
Is this a duplicate of #63?

**Comment by davidjrh** [comment]
Yep, I should have reviewed the other opened issues before. Adding the comment with the Azure Pipelines outbound addresses on that thread.
